server:
  port: 8002
spring:
  application:
    name: cloud-provider # 对外暴露的统一 服务实例名 (配置多个 provider 时，需要保持一致，不可修改)
eureka:
  instance:
    prefer-ip-address: true # 使用服务 ip地址 进行注册服务
    instance-id: cloud-provider-8002 # 服务名称信息   -- Eureka 界面里 Status 下的名称
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/    # 注册到两个Eureka中，实现高可用
      #defaultZone: http://localhost:8761/eureka/

# actuator 服务检测
management:
  server:
    port: 9002
  endpoints:
    web:
      #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      #base-pat: /monitor
      exposure:
        # 开放所有页面节点  默认只开启了health、info两个节点
        include: "*"
  endpoint:
    health:
      show-details: always  #显示健康具体信息  默认不会显示详细信息
# actuator 监管服务 /actuator/info  提示信息
info:
  app.name: cloud-provider
  company.name: yusys.com.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
