server:
  port: 8201
spring:
  application:
    name: cloud-consume-feign
eureka:
  instance:
    prefer-ip-address: true # 使用服务 ip地址 进行注册服务
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/



